# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/instr_blk_mem_sim/instr_blk_mem_sim.xci
# IP: The module: 'instr_blk_mem_sim' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/instr_blk_mem_sim/instr_blk_mem_sim_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instr_blk_mem_sim'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/instr_blk_mem_sim/instr_blk_mem_sim.xci
# IP: The module: 'instr_blk_mem_sim' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/instr_blk_mem_sim/instr_blk_mem_sim_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instr_blk_mem_sim'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
