# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/xdma.xci
# IP: The module: 'xdma' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_2/xdma_v4_1_8_blk_mem_64_noreg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_8_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_8_blk_mem_64_noreg_be} -quiet] -quiet

# IP: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_1/xdma_v4_1_8_blk_mem_64_reg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_8_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_8_blk_mem_64_reg_be} -quiet] -quiet

# IP: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/xdma_pcie4_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_pcie4_ip || ORIG_REF_NAME==xdma_pcie4_ip} -quiet] -quiet

# IP: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/ip_0/xdma_pcie4_ip_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_pcie4_ip_gt || ORIG_REF_NAME==xdma_pcie4_ip_gt} -quiet] -quiet

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_2/xdma_v4_1_8_blk_mem_64_noreg_be_ooc.xdc

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_1/xdma_v4_1_8_blk_mem_64_reg_be_ooc.xdc

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/ip_0/synth/xdma_pcie4_ip_gt_ooc.xdc

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/ip_0/synth/xdma_pcie4_ip_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_pcie4_ip_gt || ORIG_REF_NAME==xdma_pcie4_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/xdma_pcie4_ip_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_pcie4_ip || ORIG_REF_NAME==xdma_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/synth/xdma_pcie4_ip_ooc.xdc

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/synth/xdma_pcie4_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_pcie4_ip || ORIG_REF_NAME==xdma_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/source/ip_pcie4_uscale_plus_x1y2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_pcie4_ip || ORIG_REF_NAME==xdma_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/xdma_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/source/xdma_pcie4_uscaleplus_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/synth/xdma_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/xdma.xci
# IP: The module: 'xdma' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_2/xdma_v4_1_8_blk_mem_64_noreg_be.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_8_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_8_blk_mem_64_noreg_be} -quiet] -quiet

# IP: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_1/xdma_v4_1_8_blk_mem_64_reg_be.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_8_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_8_blk_mem_64_reg_be} -quiet] -quiet

# IP: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/xdma_pcie4_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_pcie4_ip || ORIG_REF_NAME==xdma_pcie4_ip} -quiet] -quiet

# IP: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/ip_0/xdma_pcie4_ip_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_pcie4_ip_gt || ORIG_REF_NAME==xdma_pcie4_ip_gt} -quiet] -quiet

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_2/xdma_v4_1_8_blk_mem_64_noreg_be_ooc.xdc

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_1/xdma_v4_1_8_blk_mem_64_reg_be_ooc.xdc

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/ip_0/synth/xdma_pcie4_ip_gt_ooc.xdc

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/ip_0/synth/xdma_pcie4_ip_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_pcie4_ip_gt || ORIG_REF_NAME==xdma_pcie4_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/xdma_pcie4_ip_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_pcie4_ip || ORIG_REF_NAME==xdma_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/synth/xdma_pcie4_ip_ooc.xdc

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/synth/xdma_pcie4_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_pcie4_ip || ORIG_REF_NAME==xdma_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/source/ip_pcie4_uscale_plus_x1y2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_pcie4_ip || ORIG_REF_NAME==xdma_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/xdma_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/source/xdma_pcie4_uscaleplus_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/synth/xdma_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
