# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-1862495-u200-station/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xcu200-fsgd2104-2-e
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/verilog
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/header_verilog
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/instr_blk_mem_sim
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/pr_read_mem
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/zq_calib_mem
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/instr_blk_mem
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/pr_ref_mem
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/scratchpad
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/axis_clock_converter_1
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/rdback_fifo
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma
  } {
      /home/user/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /home/user/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /home/user/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/verilog
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/header_verilog
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/instr_blk_mem_sim
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/pr_read_mem
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/zq_calib_mem
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/instr_blk_mem
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/pr_ref_mem
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/scratchpad
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/axis_clock_converter_1
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/rdback_fifo
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm
    /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma
  } {
      ./.Xil/Vivado-1862495-u200-station/realtime/instr_blk_mem_sim_stub.v
      ./.Xil/Vivado-1862495-u200-station/realtime/pr_read_mem_stub.v
      ./.Xil/Vivado-1862495-u200-station/realtime/zq_calib_mem_stub.v
      ./.Xil/Vivado-1862495-u200-station/realtime/instr_blk_mem_stub.v
      ./.Xil/Vivado-1862495-u200-station/realtime/pr_ref_mem_stub.v
      ./.Xil/Vivado-1862495-u200-station/realtime/scratchpad_stub.v
      ./.Xil/Vivado-1862495-u200-station/realtime/axis_clock_converter_stub.v
      ./.Xil/Vivado-1862495-u200-station/realtime/rdback_fifo_stub.v
      ./.Xil/Vivado-1862495-u200-station/realtime/phy_ddr4_udimm_stub.v
      ./.Xil/Vivado-1862495-u200-station/realtime/xdma_stub.v
      /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/verilog/ddr4_adapter.v
      /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/verilog/ddr4_mc_odt.v
      /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/ddr_pipeline.v
      /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/decode_stage.v
      /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/diff_shift_reg.v
      /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/exe_pipeline.v
      /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/execute_stage.v
      /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/fetch_stage.v
      /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/frontend.v
      /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/maintenance_controller.v
      /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/pop_count4.v
      /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/pre_decode.v
      /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/readback_engine.v
      /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/register_file.v
      /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/softmc_pipeline.v
      /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/verilog/softmc_top.v
    }
      rt::read_vhdl -lib xpm /home/user/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top softmc_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-1862495-u200-station/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
