# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.runs/synth_1/softmc_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcu200-fsgd2104-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.cache/wt [current_project]
set_property parent.project_path /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:au200:part0:1.3 [current_project]
set_property ip_output_repo /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/coe/pr_read.coe
add_files /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/coe/pr_zq.coe
add_files /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/coe/pr_ref.coe
add_files /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/coe/simmem.coe
add_files /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/apps/BNN/memory_init.coe
add_files /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/apps/read_write/program.coe
read_verilog {
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/verilog/project.vh
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/header_verilog/parameters.vh
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/header_verilog/encoding.vh
}
read_verilog -library xil_defaultlib {
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/verilog/ddr4_adapter.v
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/verilog/ddr4_mc_odt.v
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/ddr_pipeline.v
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/decode_stage.v
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/diff_shift_reg.v
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/exe_pipeline.v
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/execute_stage.v
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/fetch_stage.v
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/frontend.v
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/maintenance_controller.v
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/pop_count4.v
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/pre_decode.v
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/readback_engine.v
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/register_file.v
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/sources/hdl/verilog/softmc_pipeline.v
  /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/verilog/softmc_top.v
}
read_ip -quiet /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/instr_blk_mem_sim/instr_blk_mem_sim.xci
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/instr_blk_mem_sim/instr_blk_mem_sim_ooc.xdc]

read_ip -quiet /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/pr_read_mem/pr_read_mem.xci
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/pr_read_mem/pr_read_mem_ooc.xdc]

read_ip -quiet /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/zq_calib_mem/zq_calib_mem.xci
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/zq_calib_mem/zq_calib_mem_ooc.xdc]

read_ip -quiet /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/instr_blk_mem/instr_blk_mem.xci
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/instr_blk_mem/instr_blk_mem_ooc.xdc]

read_ip -quiet /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/pr_ref_mem/pr_ref_mem.xci
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/pr_ref_mem/pr_ref_mem_ooc.xdc]

read_ip -quiet /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/scratchpad/scratchpad.xci
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/scratchpad/scratchpad_ooc.xdc]

read_ip -quiet /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/axis_clock_converter_1/axis_clock_converter.xci
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/axis_clock_converter_1/axis_clock_converter_ooc.xdc]

read_ip -quiet /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/rdback_fifo/rdback_fifo.xci
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/rdback_fifo/rdback_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/rdback_fifo/rdback_fifo_ooc.xdc]

read_ip -quiet /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/phy_ddr4_udimm.xci
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/ip_1/par/phy_ddr4_udimm_phy_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/bd_0/ip/ip_0/bd_ba6a_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/bd_0/ip/ip_0/bd_ba6a_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/bd_0/ip/ip_1/bd_ba6a_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/bd_0/ip/ip_1/bd_ba6a_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/bd_0/ip/ip_2/bd_ba6a_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/bd_0/ip/ip_3/bd_ba6a_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/bd_0/ip/ip_6/bd_ba6a_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/bd_0/ip/ip_9/bd_ba6a_second_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/bd_0/ip/ip_10/bd_ba6a_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/bd_0/bd_ba6a_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/ip_0/phy_ddr4_udimm_microblaze_mcs_board.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/ip_0/phy_ddr4_udimm_microblaze_mcs_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/phy_ddr4_udimm_board.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/par/phy_ddr4_udimm.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/bd_0/ip/ip_0/data/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/ip_0/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/phy_ddr4_udimm/sw/calibration_0/Debug/calibration_ddr.elf]

read_ip -quiet /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/xdma.xci
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_2/xdma_v4_1_8_blk_mem_64_noreg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_1/xdma_v4_1_8_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/ip_0/synth/xdma_pcie4_ip_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/ip_0/synth/xdma_pcie4_ip_gt.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/xdma_pcie4_ip_board.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/synth/xdma_pcie4_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/synth/xdma_pcie4_ip_late.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/ip_0/source/ip_pcie4_uscale_plus_x1y2.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/xdma_board.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/source/xdma_pcie4_uscaleplus_ip.xdc]
set_property used_in_implementation false [get_files -all /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/xdma/synth/xdma_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/constraints/U200_C1_UDIMM.xdc
set_property used_in_implementation false [get_files /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/constraints/U200_C1_UDIMM.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top softmc_top -part xcu200-fsgd2104-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef softmc_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file softmc_top_utilization_synth.rpt -pb softmc_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
