# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/rdback_fifo/rdback_fifo.xci
# IP: The module: 'rdback_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/rdback_fifo/rdback_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'rdback_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/rdback_fifo/rdback_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rdback_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/rdback_fifo/rdback_fifo.xci
# IP: The module: 'rdback_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/rdback_fifo/rdback_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'rdback_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/rdback_fifo/rdback_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rdback_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
