# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/axis_clock_converter_1/axis_clock_converter.xci
# IP: The module: 'axis_clock_converter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/axis_clock_converter_1/axis_clock_converter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_clock_converter'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/axis_clock_converter_1/axis_clock_converter.xci
# IP: The module: 'axis_clock_converter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/workspace/SiMRA-DRAM/DRAM-Bender/projects/U200/U200.srcs/sources_1/ip/axis_clock_converter_1/axis_clock_converter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_clock_converter'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
